# Generated by Django 2.1 on 2020-06-30 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.IntegerField(unique=True, validators=[restapi.models.validate_number])),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('car_number', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Driver')),
            ],
        ),
    ]
